GET http://localhost:3000/api/folder/%2f HTTP/1.1

###

GET https://a-filer-backend.vercel.app/api/folder/%2f HTTP/1.1
Accept:*/*
Accept-Language:zh-CN,zh;q=0.9
Origin:https://a-filer-5vpl0l6bt-russell0430.vercel.app
Referer:https://a-filer-5vpl0l6bt-russell0430.vercel.app/
Sec-Ch-Ua:"Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"
Sec-Ch-Ua-Mobile:?0
Sec-Ch-Ua-Platform:"Windows"
Sec-Fetch-Dest:empty
Sec-Fetch-Mode:cors
Sec-Fetch-Site:cross-site
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36


###
OPTIONS https://a-filer-backend.vercel.app/ HTTP/1.1


###

OPTIONS  https://a-filer-backend.vercel.app:443//api/folder/%2F HTTP/1.1

